# Generated by Django 3.1.7 on 2021-04-06 02:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0001_initial'),
        ('albumuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumUsers',
            new_name='Albumuser',
        ),
    ]
