# Generated by Django 3.1.7 on 2021-04-06 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albumuser', '0003_auto_20210405_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumuser',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albumuser_album', to='album.album'),
        ),
        migrations.AlterField(
            model_name='albumuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albumuser_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
