# Generated by Django 3.1.7 on 2021-04-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0002_auto_20210403_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
