# Generated by Django 3.1.7 on 2021-04-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albumtype', '0001_initial'),
        ('albumaccess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_access', to='albumaccess.albumaccess')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_type', to='albumtype.albumtype')),
            ],
        ),
    ]
